Repository Vaibhavabhaysharma/Toggling-dashboard, pull requests merged in 2020-09, with the labels that each got.

#1 New index
  html/index.html
Labels: good first issue, help wanted

#3 table-basic 1
  html/table-basic.html
Labels: good first issue

#4 Icon_font_awesome 1
  html/icon-fontawesome.html
Labels: good first issue, help wanted

#6 blank-page 1
  html/pages-blank.html
Labels: good first issue

#5 Profile page
  html/pages-profile.html
Labels: good first issue

#7 Profile page 2
  html/pages-profile.html
Labels: good first issue

#8 profile page 3
  html/index.html
  html/map-google.html
  html/pages-blank.html
  html/pages-profile.html
Labels: enhancement

#9 Dashboard 1
  html/index.html
Labels: enhancement
